### ISSUE TITLE
Arreglar el componente de "BLOGS"

### ISSUE THREAD

**Issue by CarlosAriasLK** [karolM254/Nike#10]
**Componente dañado por error en el manejo de git**
![image](https://github.com/user-attachments/assets/6d059ca2-2b47-482a-8b67-578cbb87ee95)

**Comment by karolM254** [comment]
**Componente arreglado**
![Captura de pantalla 2024-12-12 082911](https://github.com/user-attachments/assets/5e1450c4-aced-4362-a31c-abb4a6ec2f1b)

![image](https://github.com/user-attachments/assets/c46843a4-b196-4888-ac64-14c99918e9fe)

**Comment by karolM254** [comment]
**Solución del componente**
El componente lo solucione creando un nuevo archivo llamado Eventos.jsx ya que el archivo anterior tenía varios problemas, entonces la mejor opción que vi en ese momento fue crear un nuevo archivo que tuviera el mismo código pero con diferentes clases ya que si colocaba las mismas clases anteriores me daba error y aparecía igual al componente con errores.
