### ISSUE TITLE
Error a corregir - Men Products page

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#108]
Arreglar el slider inferior de la sección de hombres de acuerdo al mockup

![Captura de pantalla 2024-12-17 175056](https://github.com/user-attachments/assets/a66c2cc5-8e9c-4e8a-8943-02d50f894f39)

**Ejemplo a seguir (Mockup) :**

![Captura de pantalla 2024-12-17 175306](https://github.com/user-attachments/assets/b65f62eb-58e7-4008-b920-b54289850c02)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/c1865048-df47-400e-a16d-49159d2c5061)
**Corregido**, se cambiaron los estilos del slider.
