### ISSUE TITLE
Arreglar componente "NinosProducto"

### ISSUE THREAD

**Issue by CarlosAriasLK** [karolM254/Nike#11]
**Falta codificación.**
![image](https://github.com/user-attachments/assets/34556267-9ff1-4c73-a796-ac47504105a9)

**Comment by karolM254** [comment]
**Componente arreglado**
![image](https://github.com/user-attachments/assets/c3cda37c-dbb8-4d09-bd74-07dbbdf10adc)

**Comment by karolM254** [comment]
**Componente arregaldo**
![Captura de pantalla 2024-12-12 112000](https://github.com/user-attachments/assets/5c5fabd4-7ca6-4a67-9f9d-ee1666e0e585)

**Comment by karolM254** [comment]
**Solución del componente**
El componente estaba fallando en la parte de los estilos al momento que se subió al repositorio, entonces lo solucione teniendo en cuenta cada clase del componente donde les coloque margin-top para bajar un poco la información y también le coloque un position: relative al hr para poder bajarlo y le coloque un margin para los lados.
