### ISSUE TITLE
Secciones con diseño incoherente

### ISSUE THREAD

**Issue by Kevinx7276** [karolM254/Nike#110]
1. En las secciones de Mujeres, Niños, Deportes tienen incoherencias en los inputs, selects, precios, tamaños.
Recomendacion: Seguir de ejemplo el mockup codificado de hombres y continuar ya que cada seccion es diferente en algunos aspectos

Mujeres:
![image](https://github.com/user-attachments/assets/e304a846-061e-4209-837b-4ac5c007b874)
![image](https://github.com/user-attachments/assets/03509d6d-6e6e-4ccd-82f4-14a084b186fc)
Niños:
![image](https://github.com/user-attachments/assets/b0bff850-b1ab-4701-9c83-7f7383d45e47)
![image](https://github.com/user-attachments/assets/34281337-a81b-471d-a016-7a3846391693)
Deportes:
![image](https://github.com/user-attachments/assets/1d0ff5a1-7cb9-4da9-a363-f44ed29ea6a7)
![image](https://github.com/user-attachments/assets/5e8d0a65-7bff-429b-b68c-304f49f58d33)

2. Diferente precio en las secciones de niños y deportes (este es un ejemplo)
![image](https://github.com/user-attachments/assets/e27e50c9-9b98-4b86-9fa2-85c75a357224)
![image](https://github.com/user-attachments/assets/4b4d96d0-3a1b-47ce-b4ff-b6065e0d6a81)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/62c3b0cb-382c-4e31-a699-caa379ce8321)
![image](https://github.com/user-attachments/assets/3e58162e-bb96-4919-a0a9-939c347be800)
1. Se han cambiado los tamaños de los inputs, tambien se cambio la posicion del boton, se arreglo el slider

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/ab6692d5-9979-41c2-8628-f32d768db88f)
![image](https://github.com/user-attachments/assets/8290c248-d29a-495c-af77-2e5477d9dcb2)
2. Se han cambiado los tamaños de los inputs, tambien se cambio la posicion del boton, se arreglo el slider, tambien se corrigeron los precios

**Comment by Marin2007** [comment]
![Captura de pantalla 2024-12-18 082447](https://github.com/user-attachments/assets/0134d408-d398-4bd7-bc17-ba295a8d909b)
