### ISSUE TITLE
Errores a corregir - Landing Page

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#20]
1. El Header es diferente al modelo mostrado. Los títulos son diferentes al del ejemplo.
**Codificado :**
![Header_original](https://github.com/user-attachments/assets/9f9c93c3-0bf7-48bc-93de-0ea78bebcef2)
**Ejemplo :**
![Header_ejemplo](https://github.com/user-attachments/assets/aee6ed4b-cabc-4342-844e-6ff5a22e071f)

###################################################################################################

2. Tipo de letra diferente  en los párrafos de la Landing page, el tipo de letra usado es Roboto y El tipo de letra a usar es Montserrat. Ubicación de precio incorrecto debajo de PHANTOM VISION ELITE. Texto del Footer es Montserrat
**Codificado :**
![Captura de pantalla 2024-12-12 204720](https://github.com/user-attachments/assets/74702c44-a005-4635-bf30-aa389e5234cd)
![Captura de pantalla 2024-12-12 205029](https://github.com/user-attachments/assets/32e15413-7d57-43c4-bcde-95b8a1d80e34)

**Ejemplo :**
![Captura de pantalla 2024-12-12 204749](https://github.com/user-attachments/assets/20e6b122-e55d-4ac6-9ffb-a7e8db6e3b5c)
![Captura de pantalla 2024-12-12 205044](https://github.com/user-attachments/assets/f8e85d58-1a13-4538-bc60-4fdf41592edb)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/5fab91ea-1fd4-4bac-b833-2e3903531054)
**Resuleto**, lo resolvi aumentandole el tamaño al font-size y le asigne el valor de 11rem; lo mismo hice con el
  line-height y le agregue un valor de 9rem;

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/9697ba47-b51d-4ca3-9114-77d82691c768)
**Resuelto**, Lo resolvi agregando el tipo de fuente correspondiente a la letra, tambien organize la parte de los precios que estaban mal posicionandos agregando el siguiente codigo

 .banner__content .price {
  font-size: 1.2rem;
  font-weight: 600;
  color: var(--text-dark);
  margin-bottom: 1rem;
  display: flex;
  align-items: center; /* Alinea verticalmente los elementos */
  position: relative;
  left: -10rem;
}

.banner__content .price span {
  font-size: 2rem;
  font-weight: 800;
  color: var(--primary-color);
  margin-right: 1rem; 
  position: static; 
  font-family: "Montserrat", sans-serif;
}

.banner__content .price del {
  font-size: 1.2rem;
  color: var(--text-dark); /* Color gris para tachado */
  text-decoration: line-through;
  margin-left: 0.5rem; /* Ajusta espacio después del precio nuevo */
  font-family: "Montserrat", sans-serif;
}
