### ISSUE TITLE
Header-Seccion de hombres-Footer

### ISSUE THREAD

**Issue by Kevinx7276** [karolM254/Nike#24]
1.Desplegable del header de cada seccion esta mal acomodado y el tipo de letra esta diferente al del mockup (tipo de letra usado en la codificacion roboto/ Tipo de letra a usar es monserrat) y el foot size tiene una linea intermedia entre los tipos de medida

2. En cada seccion del header a la hora de haber sido seleccionado deberia de mantenerse en color azul oscuro

programado:
![image](https://github.com/user-attachments/assets/ee718b41-bc22-4ec6-8352-e079c881bb2c)

ejemplo:
![image](https://github.com/user-attachments/assets/d95893a3-e79a-42b0-9980-e5d3d05b1604)

3. Contenedor de las imagenes de los zapatos de la seccion de hombres esta inecesariamente grande 

![image](https://github.com/user-attachments/assets/b246795b-e690-46f9-bb65-dcb66a53dae9)

4. Buscador tiene un background blanco por lo cual no coincide con el del mockup(remover el background del buscador)

![image](https://github.com/user-attachments/assets/0aa06120-6f68-4a06-a9c0-0a5945c55402)

5. El footer cuando se entra a cada seccion (hombres, mujeres, niños, marcas)  los iconos del footer al lado de la parte del copyright se ven azules y en el original son blancos

programado:
![image](https://github.com/user-attachments/assets/66cd9e73-f0fd-4fa1-bc55-39791694f842)

ejemplo:
![image](https://github.com/user-attachments/assets/03cc2bd7-15e6-4f08-92ad-80eef6b76f1e)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/3723bf94-3501-47b3-a956-d146be366460)
4.**Resuelto**, lo resolvi poniendole un color transparente al div que esta de fondo.

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/9d19bf14-70d5-482b-ad76-da2cbff460d7)
5. **Resuleto**, lo solucione cambiandole el color a los iconos, agregando un nuevo bloque de codigo

**Comment by karolM254** [comment]
**Solución del header**
![image](https://github.com/user-attachments/assets/e6f73094-a977-422d-8cbc-3dd1f524991a)
lo resolví organizando las siguientes clases /* Dropdown Menu */
.contenido-women {
    display: grid; 
    position: absolute;
    top: 3rem;
    left: 0;
    padding: 20px;
    z-index: 1000;
    background-color: #020a14;
    width: 100%;
    grid-template-columns: repeat(11, 1fr);  /*5, 1fr*/
    gap: 10px;
    opacity: 0;
    visibility: hidden;
    transition: opacity 0.3s ease-in-out, visibility 0.3s ease-in-out;
}
donde agregue el grid-template-columns: repeat(11, 1fr);  /*5, 1fr*/   gap: 10px;
    opacity: 0;
    visibility: hidden;
/* Styling para las secciones internas del dropdown */
.contenido-women div {
    color: #ddd;
    padding: 5px;
    margin: 0;
    /* para mover los submenus*/
    position: relative;
    left: 50px;
} y agregando     /*Styling para mover los submenus*/
    position: relative;
    left: 50px;
