### ISSUE TITLE
Productos-Hombre

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#25]
1. La fuente de montserrat no está siendo cargada por el font-family porque los estilos están llamando al font-heading.
 El tipo de letra es diferente. 

El botón de añadir al carrito está todo en mayuscula y en negrilla y en el mockup está diferente.

2. La linea azul está ocupando toda la pantalla y en el mockup ocupa un 80% mas o menos

3. Las imagenes de la parte de abajo están aplastadas y faltan las flechas para el slider.
4. El slider está funcionando tactilmente, cambiarlo a  flechas.

Codificado:

![image](https://github.com/user-attachments/assets/6eb469a5-cec7-4afb-a2af-e530fa60b2cf)

Ejemplo:

![image](https://github.com/user-attachments/assets/d0d4b749-4ce7-46e9-8d61-077160a45ed4)

5. La descripción está incompleta.
6. La X para cerrar la descripción es azul y en el mockup es negra

Codificado: 

![image](https://github.com/user-attachments/assets/d93d6fa4-a13b-4663-85b8-e0ddee96d8e9)

Ejemplo: 

![image](https://github.com/user-attachments/assets/8c530b0c-89ac-439d-badf-debdd0b02a53)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/ac1b1b1a-be84-4fc9-9310-9b46da1fada1)

1. **Resuelto**, Lo resolvi asignandole el tipo de letra que esta definida en los mock-ups

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/5875391a-f1de-443f-84d8-5116d8a5515e)
**Solucionado**, Lo solucione poniendo la letra en minuscula y quitandole la negrilla, tambien posicione el boton en el lugar que se muestra en los mockups

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/dbc6b8fd-ea1a-4a92-82f7-7b39d91edc62)
2.**Resuelto**, lo resolvi cambiando el tamaño a la linea

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/7b39efb2-a313-44fa-a71c-5b62558cf8f2)
3. **Resuelto** lo resolvi cambaindole el tamaño a las imagenes.
4.  **Resuelto**  cambie el valor de la distancia de las felchas que eso era lo que hacia que las flechas no se vieran.

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/939f58df-e3a1-459a-9caa-251d2cf72791)
5.**Resuleto**, lo arregle agragando las descripciones a los productos.

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/05c4cfb7-1dc5-4c5b-8c2c-41dcc578b775)
6. **Resuelto**, lo resolvi cambiandole el color a la x
