### ISSUE TITLE
¡ IMPORTANTE ! --- Fuentes

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#26]
1. Ajustar las fuentes del proyecto acorde a los mockups.

**Comment by karolM254** [comment]
**Está en proceso**

**Comment by Laucrv** [comment]
**Fuentes corregidas** 
Se ajustaron las fuentes de todo el proyecto, usando Google fonts los títulos tienen una fuente 'Roboto Condensed' y los párrafos 'Montserrat'.
