### ISSUE TITLE
Errores a corregir ----- Productos-Mujeres

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#27]
1. El buscador de productos de mujeres es diferente a los demas.
![image](https://github.com/user-attachments/assets/7bea6893-9621-4d58-9a86-6ac5fde3dbfa)

2. Los inputs son diferentes al del mockup.

![image](https://github.com/user-attachments/assets/ad81c0ac-d56f-45b8-b2a3-093e9074f106)

3. Hacer un slider en la seccion de productos-mujeres cuando se selecciona un zapato.

![image](https://github.com/user-attachments/assets/7f4f4490-e798-43d8-b934-93c9a6be7457)

4. En cada sección del proyecto se utiliza un esquema diferente. Se recomienda unificar el diseño basándose en un único esquema para garantizar coherencia visual en toda la página.

5. La descripción está diferente a la del mockup.

![image](https://github.com/user-attachments/assets/468e0da0-c861-4a73-9571-c184631e887e)

6. En todas las secciones es necesario que se indique claramente en cuál nos encontramos. Para mejorar la organización y visualización, se recomienda diseñar los mockups que muestren donde nos encontramos.

![image](https://github.com/user-attachments/assets/60f0dd20-ac20-451d-afd0-67ab6e6927f9)

**Comment by karolM254** [comment]
**1. Solución del buscador**
![image](https://github.com/user-attachments/assets/acc4c7fb-b46a-4e64-a17f-0c3f85f7f51f)
Se solucionó colocándole a la clase del input un background-color: transparent;

**Comment by karolM254** [comment]
**2. Solución inputs** 
![image](https://github.com/user-attachments/assets/a9e0f286-7416-4679-824b-b49106784c70)
Se soluciono colocándole los siguientes estilos a esta clase .select-mujeres {
  width: 24%;
  margin: 1px 0;
  padding: 8px;
  font-size: 14px;
  border-radius: 50px;
  background-color: #ececec;
  cursor: pointer;
  border: none;
  position: relative;
  top: 15px;
} se agrego el background-color: #ececec;  padding: 8px; margin: 1px 0;

**Comment by karolM254** [comment]
**3. Solución sobre el slider**
![image](https://github.com/user-attachments/assets/35e8b140-75fd-4d03-89b2-c77103a3604c)
Se soluciono agregando las fechas de los lados const CustomNextArrow = (props) => {
    const { style, onClick } = props;
    return (
      <div
        style={{ ...style, display: "block", position: "absolute", right: "8px", top: "45%", cursor: "pointer", zIndex: 2 }}
        onClick={onClick}
      >
        <i className="ri-arrow-right-circle-fill" style={{ color: "#1e40af", fontSize: "30px" }}></i>
      </div>
    );
  };  // Componentes para las flechas personalizadas
  const CustomPrevArrow = (props) => {
    const { style, onClick } = props;
    return (
      <div
        style={{ ...style, display: "block", position: "absolute", left: "8px", top: "45%", cursor: "pointer", zIndex: 2 }}
        onClick={onClick}
      >
        <i className="ri-arrow-left-circle-fill" style={{ color: "#1e40af", fontSize: "30px" }}></i>
      </div>
    );
  }; se agrego la siguiente contante para el tamaño del slider  const settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 3,
      slidesToScroll: 1,
      prevArrow: <CustomPrevArrow />,
      nextArrow: <CustomNextArrow />,
      responsive: [
        {
          breakpoint: 768, // Para pantallas pequeñas
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1,
          },
        },
      ],
    }

**Comment by karolM254** [comment]
**4. El mismo esquema de los demás slider**
Se solucionó organizando los estilos como se encuentra en la parte de Wen para que tengan el mismo esquema y no sean diferentes.

**Comment by karolM254** [comment]
**5. Solución del modal con la descripción**
![image](https://github.com/user-attachments/assets/64bfd4b8-fa9d-49f3-8594-bcec56ecff73)
Se soluciono colocándole clases con el nombre acorde al archivo de Women, ya que otras clases de otros archivos lo estaban perjudicando, más que todo clases globales.
