### ISSUE TITLE
Errores a corregir - Kids section

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#28]
1. Separar un poco las imágenes laterales de las flechas de desplazamiento ubicadas a ambos costados.

![Captura de pantalla 2024-12-13 001643](https://github.com/user-attachments/assets/02e6b89f-97c1-4f09-b7f8-62e33b9bb502)

2. Como en las descripciones anteriores, sigan el mismo esquema para organizar la información del producto.

![Captura de pantalla 2024-12-13 001836](https://github.com/user-attachments/assets/6760fdfd-4fb1-4860-92c5-3bc0ece71b94)

**Comment by gaby0512** [comment]
1. Se le redujo el tamaño a las imagenes con un width: 90% y un height: 35vh
![1](https://github.com/user-attachments/assets/df528d0b-9634-404e-b439-cfe952d83fcb)
2. Se le puso un margin-bottom de 30px a el h3 (Descripción)
![2](https://github.com/user-attachments/assets/808f8207-32a2-41cf-9f8d-a33a7056369e)
