### ISSUE TITLE
Errores a corregir-Brands

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#31]
1. El título "Nuestras Marcas" es más pequeño que el del mockup, el texto no está bien estructurado, no son idénticos y la fuente utilizada no es la correcta (debería ser Horizon). Además, los logos están demasiado grandes. Se deben ajustar estos elementos para que sean consistentes con el diseño del mockup.

Codificado:

![image](https://github.com/user-attachments/assets/5319f436-6b32-41ac-83a3-d8c66b0ea1f0)

Ejemplo:

![image](https://github.com/user-attachments/assets/ae3a5d2f-ecb3-4fa7-b2b5-a98475752254)

2. La sección "Creamos el futuro del deporte" presenta varios problemas: el tamaño de la letra es más pequeño que el del mockup, la fuente utilizada no coincide, la imagen no tiene las mismas proporciones que el mockup y carece de border-radius. Es necesario ajustar estos elementos para que se alineen con el diseño establecido en el mockup.

Codificado:

![image](https://github.com/user-attachments/assets/37fe33cd-7489-41f3-bb02-821187fd3a87)

Ejemplo:

![image](https://github.com/user-attachments/assets/6dc53e0a-976f-457f-ba9c-63a0beb2130f)

3. En la sección "Tributo a la grandeza", se identifican los siguientes problemas: el logo no está centrado, el título no tiene el mismo tamaño que en el mockup, el texto tampoco está centrado ni tiene el tamaño correcto, la imagen es un poco más pequeña de lo debido y no cuenta con border-radius.

Codificado:

![image](https://github.com/user-attachments/assets/a4b6b488-33c5-4aff-8f10-ca040fc18e57)

Ejemplo:

![image](https://github.com/user-attachments/assets/0a2e1ef7-acd7-403f-b7bf-af854590380b)

4. En la sección "Cien años en el juego", el tamaño de la letra no coincide con el mockup, la imagen no tiene border-radius, el párrafo necesita estar un poco más hacia la izquierda y la fuente utilizada no es la correcta.

Codificado:

![image](https://github.com/user-attachments/assets/689a96b4-1b09-4678-b09c-3d3e921362ec)

Ejemplo:

![image](https://github.com/user-attachments/assets/891f5e24-21a3-4ae8-9d52-9c87994a4c82)

**Comment by sebastianmontoya04** [comment]
Correcion 1: El título "Nuestras Marcas" ya es mas grande, el texto ya está bien estructurado, los logos están con el tamaño adecuado; y los elementos ya son consistentes con el diseño del mockup.

muckup:
![Captura de pantalla 2024-12-13 095428](https://github.com/user-attachments/assets/39b81289-0ccf-4db7-9c7e-1d50406f3d59)

codificado:
![Captura de pantalla 2024-12-13 095240](https://github.com/user-attachments/assets/a9f2cd36-8a52-4d50-aac0-f1078fa8efb4)


Correccion 2: En la sección "Creamos el futuro del deporte" el tamaño de la letra ya es mas grande, la imagen ya tiene las mismas proporciones que el mockup y tiene border-radius. 

muckup:
![image](https://github.com/user-attachments/assets/588ad540-11a3-48bb-ae44-e0599ea97699)

codificado:
![Captura de pantalla 2024-12-13 100243](https://github.com/user-attachments/assets/17735349-67ab-4aeb-afd0-7de8d95c9ad9)

Correccion 3: En la sección "Tributo a la grandeza" el logo ya está centrado, el título tiene el mismo tamaño que en el mockup, el texto está centrado y tiene el tamaño correcto, la imagen cuenta con border-radius.

muckup:
![Captura de pantalla 2024-12-13 101932](https://github.com/user-attachments/assets/1b169ac1-9625-4cc6-85d4-84967dfa314a)

Codificado:
![Captura de pantalla 2024-12-13 101608](https://github.com/user-attachments/assets/07b43a52-1a0f-48d9-a03d-2f1e3e3c0c7b)

Correccion 4: En la sección "Cien años en el juego", el tamaño de la letra coincide con el mockup, la imagen tiene border-radius, el párrafo esta más hacia la izquierda.

muckup:
![Captura de pantalla 2024-12-13 102823](https://github.com/user-attachments/assets/ce78bc07-9a87-4ac4-a84d-292c08e999dc)

Codificado:
![Captura de pantalla 2024-12-13 102908](https://github.com/user-attachments/assets/4a4f5745-0ffb-429d-a414-82f6d8d3254a)
