### ISSUE TITLE
Errores - Customize Page

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#32]
El tipo de letra en los diversos inputs está diferente a la seleccionada en los mockups, al hacer click en algún calzado de la derecha no se bordea con una línea azul oscura, los placeholders no tienen un grado bajo de transparencia, al hacer la selección en los select no se le aplica una negrilla a la selección, el botón de agregar al carrito se desborda al footer, al desplegar la información del producto esta se encuentra desordenada a parte de que se desborda hacia el footer, el titulo de los diversos productos laterales debe de estar en mayúscula sostenida.

![Captura de pantalla 2024-12-13 020926](https://github.com/user-attachments/assets/5e0ffa23-4440-4d78-8e19-81ea9156fac1)
![Captura de pantalla 2024-12-13 021131](https://github.com/user-attachments/assets/916b6411-45b6-4e6d-bf6a-9a2b28d195a5)

**Comment by Marialejandra2368** [comment]
**Resuelto: Estaba en minúscula y lo cambie a mayúscula. ** 
![image](https://github.com/user-attachments/assets/407f31fb-2020-453e-b717-d246eaa36e08)

**Comment by Marialejandra2368** [comment]
**Resuelto:** El tipo de fuente no era el correcto estaba en "roboto" y en el mockup esta en montserrat corregido
![image](https://github.com/user-attachments/assets/d560cd54-6577-4147-adf9-0fd7239b5cdc)

**Comment by Marialejandra2368** [comment]
Resuelto: El tipo de fuente no era el correcto estaba en "roboto" y en el mockup esta en montserrat corregido
![image](https://github.com/user-attachments/assets/293db22e-537e-4479-9ace-09a88154c7ac)

**Comment by Marialejandra2368** [comment]
Resuelto: El tipo de fuente no era el correcto estaba en "roboto" y en el mockup esta en montserrat corregido
![image](https://github.com/user-attachments/assets/6361efde-dcbc-42f6-b17d-1e8ebc5af926)

**Comment by Marialejandra2368** [comment]
Resuelto: cambie la imagen del carrito para que quede igual del mockup
![image](https://github.com/user-attachments/assets/360b1540-949f-4b4c-8c79-810caef00847)

**Comment by Marialejandra2368** [comment]
**Resuelto:**  al hacer click en algún calzado de la derecha se bordea con una línea azul, implemente un input el cual es un evento que al darle click en la imagen sale el borde.
![image](https://github.com/user-attachments/assets/564be769-ff64-4cb7-868c-cf1b8359b6fe)

**Comment by Marialejandra2368** [comment]
**Resuelto:** Los tamaños de fuente y la fuente quedaron modificadas estaban en "roboto" y quedaron en "monserrat" el color de los input en las "selecciones" quedaron igualmente establecidas como estan en los mockups.
![image](https://github.com/user-attachments/assets/12cc0a19-41b1-47e8-b57a-890078bb6a72)

**Comment by Marialejandra2368** [comment]
**Resuelto:** Como pueden observar ya se nota la transparencia al darle click en " Ver la información del producto" y sale el modal totalmente modificado cambie las clases y las coloque como nombre aleja, trejos .
Agregue el Background color y le di el transparente  a la pagina al 100%, cambie el tamaño de fuente con Font-size y su fuente respectiva "Open sans"con Font-familiy.
 Para el contenedor agregue un Padding  y un Width para reducir el espacio del contenedor y el ancho de este.
También podemos apreciar que ya no se desborda el Footer ni el botón "Agregar al carrito"
![image](https://github.com/user-attachments/assets/f4d5e996-8dfb-4fa7-8bfe-eddca7e4cf75)

**Comment by Marialejandra2368** [comment]
**Resuelto:** Implementamos junto con mis compañeros el botón de volver en las paginas.
![image](https://github.com/user-attachments/assets/c30381b1-a00b-481f-98e5-f66b61c152de)
