### ISSUE TITLE
Errores a corregir ---- Sobre-nosotros / Fabricantes-Nike

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#35]
1. En sobre nosotros solo falta la linea de separación.

Codificado:

![image](https://github.com/user-attachments/assets/9ef7c94f-b1ee-4f52-8339-62a3db7eb750)

Ejemplo:

![image](https://github.com/user-attachments/assets/41749053-90b4-4e1a-a474-bb77257b7b68)

2. En la sección de fabricantes lo unico sería el texto que esta mas largo que en el mockup.

Codificado:

![image](https://github.com/user-attachments/assets/c684c1f3-1d43-432b-bcc6-577ddc70e000)

Ejemplo:

![image](https://github.com/user-attachments/assets/274ef314-33d7-4905-a69b-8f43eec30474)

**Comment by karolM254** [comment]
**Solución de la línea de sobre nosotros**
![image](https://github.com/user-attachments/assets/b36218f5-5a7a-4665-9846-1424375f1f06)
La línea no quería aparecer ya que en otro archivo había un hr con estilos globales por eso esta línea no quería aparecer, ingrese al archivo sobre nosotros inspeccione y por eso me di cuenta del hr con estilos globales fui al archivo del hr global le coloque una clase y ya salía la línea en sobre nosotros fui a los estilos y le coloque el color gris.

**Comment by karolM254** [comment]
**Corrección en la parte de fabricantes**
![image](https://github.com/user-attachments/assets/80e4b648-7760-42fd-a987-98c5d8821b97)
El error lo solucione colocándole una clase al p que contenga los siguientes estilos .tarjeta-contenido .tarjeta-contenido-parrafo {
    text-align: justify;
    margin: 0 5px;
    padding: 5px;
    font-size: 14px;
    line-height: 1.6;
    max-width: 600px;
}
