### ISSUE TITLE
Errores a corregir - Blogs Page

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#36]
Arreglar el tamaño base de la página para una correcta visualización de las flechas de desplazamiento laterales en la parte inferior de la página, además de agregarlas a los mockups.

![Captura de pantalla 2024-12-13 032235](https://github.com/user-attachments/assets/8776ac82-46ba-4d2a-a423-f7397909331b)

**Ejemplo a seguir :**

![Captura de pantalla 2024-12-13 032829](https://github.com/user-attachments/assets/eecc4818-65ff-4882-bcd4-2e652908edf2)

Organizar correctamente el orden de la descripción de los eventos.

![Captura de pantalla 2024-12-13 031822](https://github.com/user-attachments/assets/33dcccf1-0393-43ea-8563-42319b8ed2d2)

**Ejemplo a seguir :**

![Captura de pantalla 2024-12-13 032541](https://github.com/user-attachments/assets/9248c49e-5ed0-4db8-b9a2-a3f46e31e911)

**Comment by karolM254** [comment]
**Correciones de la parye de blogs**
![image](https://github.com/user-attachments/assets/454efca7-1182-4857-bd17-bcc05d699203)
**Corrección del modal**
![image](https://github.com/user-attachments/assets/de53ca68-5ed9-4609-8cd1-143032a76ed7)
soluciones: 
Para solucionar el error le di a la pantalla inspeccionar y le di clic en el modal y me aparecía una clase diferente a la que yo le tenía y me di cuenta de que esa misma clase la tiene un modal de Alejandra entonces para solucionar el problema le cambié el nombre a todas mis clases del modal y así dio.
