### ISSUE TITLE
Errores a Corregir - Políticas de Privacidad

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#38]
Agregar el botón de volver en la parte superior izquierda de la página.

![Captura de pantalla 2024-12-13 033425](https://github.com/user-attachments/assets/c066bb16-4dcb-41e5-b9e3-92dc469b6ea0)

**Ejemplo a seguir :**

![Captura de pantalla 2024-12-13 033452](https://github.com/user-attachments/assets/57e33b7a-1926-45cc-8dd1-f6f8d1177ebc)

Cambiar la transparencia de la fecha de publicación de las políticas.

![Captura de pantalla 2024-12-13 033546](https://github.com/user-attachments/assets/fdf64e9a-bb41-4ad8-bdd3-ac8378339627)

**Ejemplo a seguir :**

![Captura de pantalla 2024-12-13 033530](https://github.com/user-attachments/assets/e9961d14-e135-470f-a275-d2fbe3827553)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/6bd44aab-d075-48d8-b762-2b78ef735919)
**Resuelto**, se resolvio cambiandole el tamaño al max-with asigandole un valor de 1000px
