### ISSUE TITLE
internacionalización

### ISSUE THREAD

**Issue by Kevinx7276** [karolM254/Nike#40]
1. Falta la internacionalización de la pagina

![image](https://github.com/user-attachments/assets/540a916b-752b-4ba3-9c76-0c7622473a9a)

**Comment by Laucrv** [comment]
**Implementación de la internacionalización**

Se creó un menú desplegable, el cual muestra dos opciones de idioma y el que esté seleccionado se distingue con un checkmarck (✔️)

![image](https://github.com/user-attachments/assets/7ad23b79-d6dd-4a8c-a7c2-8b5afd88639f)
