### ISSUE TITLE
Falta botón volver 

### ISSUE THREAD

**Issue by SEB4S-DL** [karolM254/Nike#41]
En la sección de carrito, falta un botón para volver a la pantalla women.
![image](https://github.com/user-attachments/assets/3bd023c0-6dbc-44f0-b068-f35328ad89b3)

**Comment by Laucrv** [comment]
**Botón de devolver en carrito integrado**

Lo resolví agregando un onClick, dándole una clase distintiva y sus estilos. El botón hará que el usuario pueda devolverse a la sección en la que estaba anteriormente.

![image](https://github.com/user-attachments/assets/77911e98-0de4-40cb-ae80-86cc0269a574)
