### ISSUE TITLE
Seguir un mismo ESQUEMA 

### ISSUE THREAD

**Issue by Kevinx7276** [karolM254/Nike#56]
1.En la ventana cuando uno selecciona un producto debe seguirse un mismo **ESQUEMA** (tipografía, tamaño de letra, tamaño de imágenes ,etc) 

mujeres:
![image](https://github.com/user-attachments/assets/97b9d585-8796-4838-a352-3a8c1720a86c)

hombres:
![image](https://github.com/user-attachments/assets/f989b423-6aa7-4070-a252-8731fd45542a)

niños:
![image](https://github.com/user-attachments/assets/f433359a-1c55-43ca-9235-9fe52fd338d8)

2.Seguir un mismo **ESQUEMA** a la hora de elegir un producto, En el desplegable debe poderse seleccionar el producto de los sliders (en todas las categorías)

mujeres:
![image](https://github.com/user-attachments/assets/34b73696-cd59-484f-a0b2-add39543889c)

hombres:
![image](https://github.com/user-attachments/assets/ace7ee50-d170-4c28-a3a0-dad91378c226)

niños:
![image](https://github.com/user-attachments/assets/01c03102-9e7f-4656-9e60-e9a83c1bfc46)

3.Cuadro de descripción de todas las categorías es diferente al de los mockup.

Codificado:
![image](https://github.com/user-attachments/assets/0d4f0501-31d1-4f7f-9cdd-3f49a1203c6e)

Mockup:
![image](https://github.com/user-attachments/assets/e3da886f-145c-45a3-ab9b-239c85de0c33)

4.Organizar los mockups de una forma lineal y coherente 
ejemplo:

mockup 1:
![image](https://github.com/user-attachments/assets/4223f1de-bb34-4dfe-bb8d-e3e43b15c868)

mockup 2:
![image](https://github.com/user-attachments/assets/55cb7c86-d6cd-4ba2-9aa5-d0af37331181)

En el mockup 1 se ven cosas diferentes o fuera de lugar que cambian drásticamente en el mockup 2 (Falta de flechas de slider, botones que faltan, etc). Revisar los mockups

**Comment by karolM254** [comment]
**1. Mismo esquema y mismo tamaño de imagen, mismo tamaño de letra, misma tipografía**
![image](https://github.com/user-attachments/assets/330f0928-db55-43c7-9096-f93220a03fb4)
![image](https://github.com/user-attachments/assets/5660e3e2-99f4-4819-92df-4e9676c6b3c4)
![image](https://github.com/user-attachments/assets/b8982bdc-ae54-4c7c-b3b2-8c4c5966cce2)
Se soluciono colocándole a las imágenes el mismo tamaño, al texto el mismo tamaño y la misma fuente, para que queden iguales.

**Comment by karolM254** [comment]
**2. Mismo esquema a la hora de seleccionar el producto**
![image](https://github.com/user-attachments/assets/df64d813-7372-48bc-8eb6-db434c5615fc)
![image](https://github.com/user-attachments/assets/5fcbdb48-8524-4cca-8bd3-72105b181979)

**Comment by karolM254** [comment]
**3. Modal corregido**
![image](https://github.com/user-attachments/assets/d3a6fc66-93da-485c-ae9c-53d141094941)
El modal se va a dejar así y se va a corregir en el mockup

**Comment by karolM254** [comment]
**4. Corregido** 
![image](https://github.com/user-attachments/assets/ea232d34-7930-40a3-bbab-209712409749)
