### ISSUE TITLE
Errores a Corregir - Customize Page

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#57]
Los Mockups de la sección de personalización de calzado son diferentes al momento de la visualización de la descripción del producto seleccionado.
**Vista original :**

![Captura de pantalla 2024-12-14 152753](https://github.com/user-attachments/assets/e1b93f0a-79d8-4d01-a69b-1c2831e4f0d8)

**Descripción :**

![Captura de pantalla 2024-12-14 152811](https://github.com/user-attachments/assets/3576d90e-1c92-4108-b12a-e73ce2431b0b)

Sigue faltando el botón de volver en la pagina programada, como en la vista de descripción, como también que el placeholder de selección de tipo de calzado empiece con el placeholder de seleccionar y en el caso de escoger un tipo como Hombre cambie el calzado recomendado en el lateral derecho, por ultimo que el precio del calzado no esté predefinido ya que debería de cambiar el precio dependiendo de la selección del usuario y que se agregue correctamente al carrito.

![Captura de pantalla 2024-12-14 152842](https://github.com/user-attachments/assets/72b28df4-3d9c-48ec-825d-b8795f79bcfc)

**Comment by Marialejandra2368** [comment]
**Resuelto:** Como hablamos el botón volver no se agrega a esta pagina e hice la corrección del modal que era innecesario y asi queda la pagina .
![image](https://github.com/user-attachments/assets/a3835bdf-ea32-40ee-acd4-0708ba48bf94)

**Comment by EGIsaac** [comment]
Cambiar el placeholder de la selección del tipo de calzado por Seleccionar... como los otros inputs

**Comment by Marialejandra2368** [comment]
**resuelto**: Se corrigió correctamente la selección del tipo de calzado por Seleccionar... 
![image](https://github.com/user-attachments/assets/1895e0fd-109a-46a3-a404-0202d4354012)

**Comment by astherdev** [comment]
cerrado.
