### ISSUE TITLE
Errores -- Header --- Footer 

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#59]
1. Los links del footer solo están funcionando algunos, no solo los de las aplicaciones.

**Codificado:** 
![image](https://github.com/user-attachments/assets/eced8829-3de2-4b05-ade7-8a417ae4b479)

2. En el header el botón del carrito no está funcionando.

**Codificado:** 

![image](https://github.com/user-attachments/assets/5966e58b-3694-4709-8991-da9e20dc8be4)

3. El filtro del header no está funcionando.

**Codificado:**

![image](https://github.com/user-attachments/assets/bc321425-ca72-4813-8aa5-d9b3752c5d00)

4. El color en donde estoy posicionado que sea de un color mas claro porque no se logra ver bien la letra.

**Ejemplo:** Estoy en la sección de Women y necesitamos que el color azul sea un poco mas claro para que la letra sea mas visible.

**Codificado:** 
![image](https://github.com/user-attachments/assets/bc321425-ca72-4813-8aa5-d9b3752c5d00)

5. Al momento de seleccionar un producto no me muestra en que sección estoy.

**Ejemplo:** En estos momentos seleccioné un zapato y no me muestra en donde estoy.

**Codificado:**

![image](https://github.com/user-attachments/assets/f6660178-9d59-4525-a9b4-d679304f5472)

**Comment by Laucrv** [comment]
**2. Botón del carrito en el header funcional**

Al dar clic al carrito de compras en el header desde cualquier sección, se llevará al usuario directamente al carrito de compras.

![image](https://github.com/user-attachments/assets/6dbba71e-edb4-4dfa-9ab8-ee1fef5e97c2)

**Comment by karolM254** [comment]
**1. Links del footer**
![image](https://github.com/user-attachments/assets/dbac1e31-a367-41c3-9b30-c87c16bd04b5)
Ya están funcionando todos los links del footer

**Comment by karolM254** [comment]
**4. Color de la letra del header** 
![image](https://github.com/user-attachments/assets/4890fee3-8f22-46d2-b0b9-b977242a4cc3)
Se soluciono colocándole un azul más claro para que se pueda notar.

**Comment by karolM254** [comment]
**2.  funcionalidad icono de carrito** 
![image](https://github.com/user-attachments/assets/0e65399a-5918-46a5-937e-803b39a9c026)
El icono del carrito ya funciona, se solucionó colocando un link con la ruta del carrito.
