### ISSUE TITLE
Eliminación del mockup de selección - Método de Pago

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#60]
Eliminar de la pantalla de los mockups la pantalla de método de pago ya que al momento de querer ir a seleccionar el método de pago se le redirige al usuario directamente a la pagina oficial de mercado pago, por lo que esta pantalla en sí no es utilizada.

![Captura de pantalla 2024-12-14 161946](https://github.com/user-attachments/assets/7c9482c5-2acf-4ab0-8773-304bed3e1bf0)

Modificar el botón de omitir por cancelar y que al momento de presionarse funcione como si le diera a la **X** en la parte superior derecha y cambiar el texto principal que pregunte: ¿ Desea continuar con el pago de su pedido o quiere seguir explorando nuestro catalogo de productos?, por lo cual **Cambiarlo también en los mockups**.

![image](https://github.com/user-attachments/assets/cc944a6e-ff80-4713-8f18-2d317ce21faa)

Eliminar los mensajes flotantes:

![Captura de pantalla 2024-12-14 163020](https://github.com/user-attachments/assets/51448fe6-cc63-4021-926d-6109c6e2ffea)
![Captura de pantalla 2024-12-14 163615](https://github.com/user-attachments/assets/85d7e744-90ac-4cd2-bef0-660f4649d070)

**Comment by gaby0512** [comment]
1. Se elimino la pantalla 
2. ⁠Se modificó el botón para que diga “cancelar” y ahora invoca “handleSkip” haciendo que el modal se cierre al hacer click. 
3. ⁠El texto principal ahora dice la frase solicitada.
![issues](https://github.com/user-attachments/assets/aee37aff-2389-4b39-8139-e6fa9e02bff2)
