### ISSUE TITLE
Errores:  MEN, WOMEN , KIDS

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#67]
Sección Men:

1. Borrar el link de ver carrito debajo del botón agregar carrito.

![image](https://github.com/user-attachments/assets/6d7f5406-6385-48f6-96c0-6758da6db87a)

2. Los párrafos están muy a la izquierda llegando a entrar a la imagen.

   
![image](https://github.com/user-attachments/assets/2057cf5a-6341-443c-8fb5-ca2626c47900)

3. El slider está en una  posición incorrecta y no está funcionando, no cambia a otro zapato cuando se selecciona y a veces se buguea.(recomendación) copiar el slider de la sección de mujeres.

![image](https://github.com/user-attachments/assets/c73416dc-30d9-463b-b9bf-e86d0bcf8cc3)

4. El carrito de la sección de hombres está bugueado por que se queda la pantalla en blanco.
5. El mensaje de ver información del producto, el párrafo de descripción es diferente al de los demás. Por favor, seguir un mismo modelo de las otras secciones. (Men , Women, Kids)
.
.
.
####################################################################################################

Sección Women:

1. Borrar el link de ver carrito debajo del botón agregar carrito.
2. Acomodar los precios del slider.
3. Por favor, para los slider hacer un cursor "Pointer" para notar que el producto pueda ser seleccionable.

![image](https://github.com/user-attachments/assets/ce01a1c4-ca76-44c6-964c-2eb1008cb62f)

####################################################################################################

Sección Kids:

1. Los inputs son diferentes a las demás secciones.
2. Cuando yo le doy al link de ver carrito sin necesidad de agregar el carrito, se agrega automáticamente al carrito (PARA TODAS LAS SECCIONES MEN, WOMEN, KIDS).
3. El botón de agregar el carrito no funciona.
4. Borrar el link de ver carrito debajo del botón agregar carrito.
5. Por favor, para los slider hacer un cursor "Pointer" para notar que el producto pueda ser seleccionable.
6. El slider no está funcionando cuando quiero seleccionar un producto no cambia.

Recomendación: Seguir un mismo modelo / esquema, si el slider esta bien hecho en la sección de Women lo pueden copiar y añadirlo a las demás secciones y hacer lo mismo con las demás cosas.

![image](https://github.com/user-attachments/assets/9727fbe8-8f5b-493f-bafd-4a0c32ed2488)

**Comment by gaby0512** [comment]
Sección Kids:
1. Se le agrego al input: font-size: 14px;   border-radius: 50px;  background-color: #ececec;  top: 15px;  margin-bottom: 20px; 
2. Se elimino el botón de ver carrito.
3. Se implementó correctamente la lógica utilizando el useCart que mantiene el estado global del carrito. La función addToCart fue modificada para verificar si el producto ya está en el carrito. Si no está, se agrega a la lista de productos en el carrito.
4. Se elimino el botón de ver carrito. 
5. Se le puso el cursor: pointer solicitado al slider.
6. Se le puso un onClick={() => navigate(`/producto_nino/${producto.id}`)} para redirigir al detalle del producto.
![issues1 1](https://github.com/user-attachments/assets/4c5b7425-0228-4efa-b487-983954b9d0ca)

**Comment by Laucrv** [comment]
**Sección mujeres**

1. Se eliminó el div que contenía el link de "ver carrito"
2. Los precios del slider se acomodaron con top en CSS
3. Cursor Pointer en las flechas del slider

![image](https://github.com/user-attachments/assets/13d4a67d-6e7b-4d2b-bc42-14226924513f)

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/a139c295-3483-4321-b6d2-4fb8c4bb5bf0)
1. **Corregido**,  lo arregle eliminando del codigo que contenia el ver carrito

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/c9b175b5-42d1-4e4f-9821-554697b08dee)
2.**Corregido**, Lo arregle acomodando las margenes de los textos

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/71921a5d-8e30-4ba0-9f9d-65c29bcef942)
3.**Corregido**, lo arregle agregandole un hipervinculo que al momento de dar click re dirija al zapato seleccionado, se corrigio la parte de cuando se daba click el slider se desplazaba hacia arriba.

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/def8d797-d9e3-4097-abd7-e6b7fa1c5ae4)
4.**Corregido**, el boton de agregar productos ya funciona, la solcuion fue enlazando los datos.

**Comment by Kev-dev-v** [comment]
![image](https://github.com/user-attachments/assets/e102f0c7-ffd5-4a48-8275-c648dcd13392)
5.**Corregido**, se implementaron los mismos estilos para el mensaje de ver "See more product information"
