### ISSUE TITLE
Errores a corregir - Sports Page

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#68]
Arreglar la sección de la descripcion del producto seleccionado

![Captura de pantalla 2024-12-15 131631](https://github.com/user-attachments/assets/caf8cd9a-8182-44b1-b51b-70a8dae8e164)

**PD:**
Al tratar de agregar un producto al carrito el producto no se agrega y al darle al botón de ver carrito debajo del botón de agregar al carrito no se redirecciona correctamente

**Comment by karolM254** [comment]
![image](https://github.com/user-attachments/assets/661e983b-7036-4278-80a2-4469a54ed0df)
Se soluciono agregando más tamaño height del modal
