### ISSUE TITLE
Errores header Parte 2

### ISSUE THREAD

**Issue by Kevinx7276** [karolM254/Nike#69]
1. Cuando uno elige una categoría (Men, Women, Kids, Sports) y luego le da a brands o customize el color de selección se duplica.

![image](https://github.com/user-attachments/assets/0f248107-c5fb-4824-8d0b-3c57dd9a0f1c)

2. El icono del carrito de compra sale de color azul en ves de salir de color blanco(debería de ser color azul cuando se seleccione el icono)

![image](https://github.com/user-attachments/assets/71001fd8-ada7-4688-9b21-d3f39bd0d5ba)

**Comment by karolM254** [comment]
**1. color de la selección de categoría** 
![image](https://github.com/user-attachments/assets/2cf804cf-8e0d-4d61-b97c-708f8372ad45)

**Comment by karolM254** [comment]
**2. Icono del carrito** 
![image](https://github.com/user-attachments/assets/fa45e621-acb4-42d4-8d05-9a8021f1090b)
Se soluciono colocándole una clase diferente a los demás y se le coloco el color blanco
