### ISSUE TITLE
Error ------ Link en el footer

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#78]
1. Hay un error en el link del footer (Customer Service  - Servicio al cliente) el cual me lleva hacia otro lado y al parecer es inexistente. Por favor, solucionarlo.

![image](https://github.com/user-attachments/assets/47dda7a0-c09a-4b0f-ad9b-4c2ff8884bb4)

**Comment by karolM254** [comment]
**1. Link correcto**
![image](https://github.com/user-attachments/assets/cb7aebc0-382a-46e0-9d18-10e5f7abbaf0)
Se soluciono cambiando la ruta
