### ISSUE TITLE
 Errores ------ Sección Men

### ISSUE THREAD

**Issue by astherdev** [karolM254/Nike#83]
1. La sección de Men tiene errores, además  no es parecida a la sección de women y kids.
2. Borrar el link de ver carrito.
3. Al momento de agregar algún producto al carrito, este se buguea y no carga la página.

![Imagen de WhatsApp 2024-12-16 a las 09 49 00_b9949928](https://github.com/user-attachments/assets/688a618f-7dae-427d-89b2-d12208d99cd3)

**Comment by karolM254** [comment]
**Solucionado**
![image](https://github.com/user-attachments/assets/ebbb57fb-15ee-4b94-aa58-dc8d677849b8)

**Comment by karolM254** [comment]
![image](https://github.com/user-attachments/assets/3b92d71b-b37d-413c-9273-7f4958cf9bb3)
