### ISSUE TITLE
Corrección de Formulario - Atención al Cliente

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#84]
Arreglar correctamente y de acuerdo al mockup el formulario de contacto al soporte:

![Captura de pantalla 2024-12-16 095317](https://github.com/user-attachments/assets/e3a916bc-322c-438d-8054-8416e6d6e647)

**Ejemplo a seguir: **

![Captura de pantalla 2024-12-16 095718](https://github.com/user-attachments/assets/20ca382d-31b2-4c7f-a77a-10e405703f01)

**Comment by karolM254** [comment]
**Solucionado**
![image](https://github.com/user-attachments/assets/d653bd95-32bd-4e67-849f-512dedd6531a)
