### ISSUE TITLE
Error en la adición de productos al carrito.

### ISSUE THREAD

**Issue by EGIsaac** [karolM254/Nike#85]
Al agregar al carrito algún producto que no sea el primer producto que se ve en la pagina igualmente se sigue agregando el mismo producto

![Captura de pantalla 2024-12-16 101330](https://github.com/user-attachments/assets/03a7c344-287e-4afb-be30-3c9aae261574)

![Captura de pantalla 2024-12-16 101348](https://github.com/user-attachments/assets/759e1df3-4cf9-4bcb-964f-32de5168503c)

**Comment by Laucrv** [comment]
Ya se agregan más productos al carrito, se solucionó cambiando un error del llamado de los productos.

![image](https://github.com/user-attachments/assets/8439a8c0-ad99-4780-8748-769a2b677f46)
